services:
    fervo_pubnub:
        class: Pubnub\Pubnub
        arguments:
            -
                publish_key: %fervo_pubnub.publish_key%
                subscribe_key: %fervo_pubnub.subscribe_key%
                secret_key: %fervo_pubnub.secret_key%
                logger: @fervo_pubnub.logger

    fervo_pubnub.twig_extension:
        class: Fervo\PubnubBundle\Twig\PubnubExtension
        arguments:
            - %fervo_pubnub.subscribe_key%
            - %fervo_pubnub.publish_key%
            - @?fervo_pubnub.uuid_provider
        tags:
            - { name: twig.extension }

    fervo_pubnub.property_path_uuid_provider:
        class: Fervo\PubnubBundle\UUIDProvider\PropertyPathUUIDProvider
        public: false
        arguments:
            - @security.token_storage
            - ~
            - true

    fervo_pubnub.logger:
        class: Fervo\PubnubBundle\Logger\PSR3Logger
        arguments:
            - @logger
        tags:
            - { name: monolog.logger, channel: pubnub }

    pubnub:
        alias: fervo_pubnub
