services:
    fervo_pubnub:
        class: Pubnub\Pubnub
        arguments:
            -
                publish_key: ~
                subscribe_key: ~
                secret_key: ~
                logger: "@logger"
        tags:
            - { name: monolog.logger, channel: pubnub }

    fervo_pubnub.twig_extension:
        class: Fervo\PubnubBundle\Twig\PubnubExtension
        arguments:
            - ~
            - ~
            - "@?fervo_pubnub.uuid_provider"
        tags:
            - { name: twig.extension }

    fervo_pubnub.property_path_uuid_provider:
        class: Fervo\PubnubBundle\UUIDProvider\PropertyPathUUIDProvider
        public: false
        arguments:
            - "@security.token_storage"
            - ~
            - true

    pubnub:
        alias: fervo_pubnub
